-- ====================================
-- DISCORD INTEGRATION TABLES
-- ====================================

-- Table to map Discord users to their Commentum roles and user IDs
CREATE TABLE discord_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Discord information
    discord_user_id TEXT NOT NULL,
    discord_username TEXT NOT NULL,
    guild_id TEXT NOT NULL,
    discord_roles TEXT[], -- Array of Discord role IDs
    
    -- Commentum integration
    user_id TEXT NOT NULL, -- Corresponding Commentum user ID
    user_role TEXT NOT NULL CHECK (user_role IN ('user', 'moderator', 'admin', 'super_admin')),
    client_type TEXT NOT NULL CHECK (client_type IN ('anilist', 'myanimelist', 'simkl', 'other')),
    
    -- Authentication token (encrypted storage)
    auth_token TEXT, -- Store the user's platform token for Discord bot actions
    
    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    last_verified TIMESTAMPTZ,
    
    -- Constraints
    CONSTRAINT discord_users_unique UNIQUE (discord_user_id, guild_id),
    CONSTRAINT discord_users_user_id_unique UNIQUE (user_id, client_type),
    CONSTRAINT discord_username_length CHECK (length(discord_username) >= 2 AND length(discord_username) <= 32)
);

-- Indexes for performance
CREATE INDEX idx_discord_users_discord_id ON discord_users(discord_user_id);
CREATE INDEX idx_discord_users_guild_id ON discord_users(guild_id);
CREATE INDEX idx_discord_users_user_id ON discord_users(user_id);
CREATE INDEX idx_discord_users_role ON discord_users(user_role);
CREATE INDEX idx_discord_users_active ON discord_users(is_active);

-- Trigger for updated_at
CREATE TRIGGER update_discord_users_updated_at 
    BEFORE UPDATE ON discord_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Row Level Security for discord_users
ALTER TABLE discord_users ENABLE ROW LEVEL SECURITY;

-- Only admins can read Discord user mappings
CREATE POLICY "Admins can read discord users" ON discord_users
    FOR SELECT USING (
        is_user_in_role(auth.uid()::text, 'admin_users') OR
        is_user_in_role(auth.uid()::text, 'super_admin_users')
    );

-- Only admins can insert Discord user mappings
CREATE POLICY "Admins can insert discord users" ON discord_users
    FOR INSERT WITH CHECK (
        is_user_in_role(auth.uid()::text, 'admin_users') OR
        is_user_in_role(auth.uid()::text, 'super_admin_users')
    );

-- Only admins can update Discord user mappings
CREATE POLICY "Admins can update discord users" ON discord_users
    FOR UPDATE USING (
        is_user_in_role(auth.uid()::text, 'admin_users') OR
        is_user_in_role(auth.uid()::text, 'super_admin_users')
    );

-- Only super admins can delete Discord user mappings
CREATE POLICY "Super admins can delete discord users" ON discord_users
    FOR DELETE USING (
        is_user_in_role(auth.uid()::text, 'super_admin_users')
    );

-- Function to verify Discord user role
CREATE OR REPLACE FUNCTION verify_discord_user_role(discord_user_id_param TEXT, guild_id_param TEXT)
RETURNS TABLE(user_id TEXT, user_role TEXT, is_valid BOOLEAN) AS $$
DECLARE
    user_record RECORD;
    required_role_ids TEXT[];
BEGIN
    -- Get the Discord user record
    SELECT du.user_id, du.user_role, du.is_active, du.last_verified
    INTO user_record
    FROM discord_users du
    WHERE du.discord_user_id = discord_user_id_param 
      AND du.guild_id = guild_id_param
      AND du.is_active = true;
    
    -- Return empty result if user not found or inactive
    IF NOT FOUND THEN
        RETURN;
    END IF;
    
    -- Return the validation result, don't just exit
    RETURN QUERY SELECT 
        user_record.user_id,
        user_record.user_role,
        CASE 
            WHEN user_record.last_verified IS NULL 
                OR user_record.last_verified < NOW() - INTERVAL '24 hours'
            THEN false
            ELSE true
        END as is_valid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to add/update Discord user mapping
CREATE OR REPLACE FUNCTION upsert_discord_user(
    discord_user_id_param TEXT,
    discord_username_param TEXT,
    guild_id_param TEXT,
    user_id_param TEXT,
    user_role_param TEXT,
    client_type_param TEXT,
    auth_token_param TEXT DEFAULT NULL,
    discord_roles_param TEXT[] DEFAULT '{}'
)
RETURNS BOOLEAN AS $$
DECLARE
    existing_user RECORD;
BEGIN
    -- Check if user already exists
    SELECT id, user_role INTO existing_user
    FROM discord_users
    WHERE discord_user_id = discord_user_id_param 
      AND guild_id = guild_id_param;
    
    IF FOUND THEN
        -- Update existing user
        UPDATE discord_users SET
            discord_username = discord_username_param,
            discord_roles = discord_roles_param,
            user_id = user_id_param,
            user_role = user_role_param,
            client_type = client_type_param,
            auth_token = auth_token_param,
            last_verified = NOW(),
            is_active = true
        WHERE id = existing_user.id;
        
        -- Log role change if different
        IF existing_user.user_role != user_role_param THEN
            INSERT INTO config (key, value) VALUES 
                ('discord_role_change_log', jsonb_build_object(
                    'timestamp', NOW(),
                    'discord_user_id', discord_user_id_param,
                    'old_role', existing_user.user_role,
                    'new_role', user_role_param,
                    'updated_by', 'system'
                )::text)
            ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
        END IF;
    ELSE
        -- Insert new user
        INSERT INTO discord_users (
            discord_user_id,
            discord_username,
            guild_id,
            discord_roles,
            user_id,
            user_role,
            client_type,
            auth_token,
            last_verified,
            is_active
        ) VALUES (
            discord_user_id_param,
            discord_username_param,
            guild_id_param,
            discord_roles_param,
            user_id_param,
            user_role_param,
            client_type_param,
            auth_token_param,
            NOW(),
            true
        );
    END IF;
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;